algorithms: [mk2_moore, dmark, mk1, crissis]
alpharange: [0.95]
drange: [4, 5, 6, 7, 8, 9, 10, 11]
graph_path: gec_ro10_mi09
l2range: [1]
lmax: 12
lrange: [4, 6, 8, 10, 12]
synch_words: ['01', '10', '111', '000']
terminations: [dmark, omega_inverted]
test: chi-squared
