# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_projectgui(object):
    def setupUi(self, projectgui):
        projectgui.setObjectName(_fromUtf8("projectgui"))
        projectgui.resize(702, 737)
        self.centralwidget = QtGui.QWidget(projectgui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 701, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.graph_path = QtGui.QLineEdit(self.tab)
        self.graph_path.setGeometry(QtCore.QRect(120, 20, 113, 27))
        self.graph_path.setText(_fromUtf8(""))
        self.graph_path.setObjectName(_fromUtf8("graph_path"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 661, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.old_term = QtGui.QCheckBox(self.groupBox)
        self.old_term.setGeometry(QtCore.QRect(30, 30, 97, 22))
        self.old_term.setObjectName(_fromUtf8("old_term"))
        self.new_term = QtGui.QCheckBox(self.groupBox)
        self.new_term.setGeometry(QtCore.QRect(110, 30, 97, 22))
        self.new_term.setObjectName(_fromUtf8("new_term"))
        self.omega_term = QtGui.QCheckBox(self.groupBox)
        self.omega_term.setGeometry(QtCore.QRect(190, 30, 97, 22))
        self.omega_term.setObjectName(_fromUtf8("omega_term"))
        self.omega_inverted_term = QtGui.QCheckBox(self.groupBox)
        self.omega_inverted_term.setGeometry(QtCore.QRect(290, 30, 121, 22))
        self.omega_inverted_term.setObjectName(_fromUtf8("omega_inverted_term"))
        self.dmark_term = QtGui.QCheckBox(self.groupBox)
        self.dmark_term.setGeometry(QtCore.QRect(440, 30, 97, 22))
        self.dmark_term.setObjectName(_fromUtf8("dmark_term"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 150, 651, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.mk1 = QtGui.QCheckBox(self.groupBox_2)
        self.mk1.setGeometry(QtCore.QRect(30, 30, 61, 22))
        self.mk1.setObjectName(_fromUtf8("mk1"))
        self.mk2 = QtGui.QCheckBox(self.groupBox_2)
        self.mk2.setGeometry(QtCore.QRect(110, 30, 61, 22))
        self.mk2.setObjectName(_fromUtf8("mk2"))
        self.dmark = QtGui.QCheckBox(self.groupBox_2)
        self.dmark.setGeometry(QtCore.QRect(340, 30, 97, 22))
        self.dmark.setTristate(False)
        self.dmark.setObjectName(_fromUtf8("dmark"))
        self.mk2_moore = QtGui.QCheckBox(self.groupBox_2)
        self.mk2_moore.setGeometry(QtCore.QRect(190, 30, 121, 22))
        self.mk2_moore.setObjectName(_fromUtf8("mk2_moore"))
        self.mk3 = QtGui.QCheckBox(self.groupBox_2)
        self.mk3.setGeometry(QtCore.QRect(450, 30, 161, 22))
        self.mk3.setObjectName(_fromUtf8("mk3"))
        self.crissis = QtGui.QCheckBox(self.groupBox_2)
        self.crissis.setGeometry(QtCore.QRect(30, 70, 71, 22))
        self.crissis.setObjectName(_fromUtf8("crissis"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 290, 651, 80))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 81, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.d_ini = QtGui.QLineEdit(self.groupBox_3)
        self.d_ini.setGeometry(QtCore.QRect(90, 30, 41, 27))
        self.d_ini.setText(_fromUtf8(""))
        self.d_ini.setObjectName(_fromUtf8("d_ini"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(150, 30, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.d_end = QtGui.QLineEdit(self.groupBox_3)
        self.d_end.setGeometry(QtCore.QRect(180, 30, 41, 27))
        self.d_end.setText(_fromUtf8(""))
        self.d_end.setObjectName(_fromUtf8("d_end"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 370, 651, 111))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.l_ini = QtGui.QLineEdit(self.groupBox_4)
        self.l_ini.setGeometry(QtCore.QRect(120, 30, 41, 27))
        self.l_ini.setText(_fromUtf8(""))
        self.l_ini.setObjectName(_fromUtf8("l_ini"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 21, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.l_end = QtGui.QLineEdit(self.groupBox_4)
        self.l_end.setGeometry(QtCore.QRect(200, 30, 41, 27))
        self.l_end.setText(_fromUtf8(""))
        self.l_end.setObjectName(_fromUtf8("l_end"))
        self.alpha_ini = QtGui.QLineEdit(self.groupBox_4)
        self.alpha_ini.setGeometry(QtCore.QRect(120, 70, 41, 27))
        self.alpha_ini.setText(_fromUtf8(""))
        self.alpha_ini.setObjectName(_fromUtf8("alpha_ini"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(170, 70, 21, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 81, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.alpha_end = QtGui.QLineEdit(self.groupBox_4)
        self.alpha_end.setGeometry(QtCore.QRect(200, 70, 41, 27))
        self.alpha_end.setText(_fromUtf8(""))
        self.alpha_end.setObjectName(_fromUtf8("alpha_end"))
        self.tag = QtGui.QLineEdit(self.tab)
        self.tag.setGeometry(QtCore.QRect(130, 490, 113, 27))
        self.tag.setText(_fromUtf8(""))
        self.tag.setObjectName(_fromUtf8("tag"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 490, 81, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.saveconfig = QtGui.QPushButton(self.tab)
        self.saveconfig.setGeometry(QtCore.QRect(230, 540, 98, 27))
        self.saveconfig.setObjectName(_fromUtf8("saveconfig"))
        self.loadconfig = QtGui.QPushButton(self.tab)
        self.loadconfig.setGeometry(QtCore.QRect(370, 540, 98, 27))
        self.loadconfig.setObjectName(_fromUtf8("loadconfig"))
        self.max_l = QtGui.QLineEdit(self.tab)
        self.max_l.setGeometry(QtCore.QRect(370, 20, 113, 27))
        self.max_l.setText(_fromUtf8(""))
        self.max_l.setObjectName(_fromUtf8("max_l"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(280, 20, 81, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.create_term = QtGui.QPushButton(self.tab_2)
        self.create_term.setGeometry(QtCore.QRect(260, 90, 151, 27))
        self.create_term.setObjectName(_fromUtf8("create_term"))
        self.create_dmark = QtGui.QPushButton(self.tab_2)
        self.create_dmark.setGeometry(QtCore.QRect(260, 200, 151, 27))
        self.create_dmark.setObjectName(_fromUtf8("create_dmark"))
        self.apply_algo = QtGui.QPushButton(self.tab_2)
        self.apply_algo.setGeometry(QtCore.QRect(260, 310, 151, 27))
        self.apply_algo.setObjectName(_fromUtf8("apply_algo"))
        self.create_term_bar = QtGui.QProgressBar(self.tab_2)
        self.create_term_bar.setGeometry(QtCore.QRect(260, 150, 151, 23))
        self.create_term_bar.setProperty("value", 0)
        self.create_term_bar.setObjectName(_fromUtf8("create_term_bar"))
        self.create_dmark_bar = QtGui.QProgressBar(self.tab_2)
        self.create_dmark_bar.setGeometry(QtCore.QRect(260, 260, 151, 23))
        self.create_dmark_bar.setProperty("value", 0)
        self.create_dmark_bar.setObjectName(_fromUtf8("create_dmark_bar"))
        self.apply_algo_bar = QtGui.QProgressBar(self.tab_2)
        self.apply_algo_bar.setGeometry(QtCore.QRect(260, 370, 151, 23))
        self.apply_algo_bar.setProperty("value", 0)
        self.apply_algo_bar.setObjectName(_fromUtf8("apply_algo_bar"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gen_seq_bar = QtGui.QProgressBar(self.tab_3)
        self.gen_seq_bar.setGeometry(QtCore.QRect(240, 260, 161, 23))
        self.gen_seq_bar.setProperty("value", 0)
        self.gen_seq_bar.setObjectName(_fromUtf8("gen_seq_bar"))
        self.gen_seq = QtGui.QPushButton(self.tab_3)
        self.gen_seq.setGeometry(QtCore.QRect(240, 200, 161, 27))
        self.gen_seq.setObjectName(_fromUtf8("gen_seq"))
        self.seq_len = QtGui.QLineEdit(self.tab_3)
        self.seq_len.setGeometry(QtCore.QRect(260, 140, 121, 27))
        self.seq_len.setObjectName(_fromUtf8("seq_len"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(260, 110, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 80, 651, 71))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.probs_l = QtGui.QLineEdit(self.groupBox_5)
        self.probs_l.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.probs_l.setText(_fromUtf8(""))
        self.probs_l.setObjectName(_fromUtf8("probs_l"))
        self.probs = QtGui.QCheckBox(self.groupBox_5)
        self.probs.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.probs.setObjectName(_fromUtf8("probs"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 160, 651, 71))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cond_probs_l = QtGui.QLineEdit(self.groupBox_6)
        self.cond_probs_l.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.cond_probs_l.setText(_fromUtf8(""))
        self.cond_probs_l.setObjectName(_fromUtf8("cond_probs_l"))
        self.cond_probs = QtGui.QCheckBox(self.groupBox_6)
        self.cond_probs.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.cond_probs.setObjectName(_fromUtf8("cond_probs"))
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(430, -30, 131, 17))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 240, 651, 71))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cond_entropy_max_l = QtGui.QLineEdit(self.groupBox_7)
        self.cond_entropy_max_l.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.cond_entropy_max_l.setText(_fromUtf8(""))
        self.cond_entropy_max_l.setObjectName(_fromUtf8("cond_entropy_max_l"))
        self.cond_entropy = QtGui.QCheckBox(self.groupBox_7)
        self.cond_entropy.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.cond_entropy.setObjectName(_fromUtf8("cond_entropy"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 320, 651, 71))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.autocorr_upto = QtGui.QLineEdit(self.groupBox_8)
        self.autocorr_upto.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.autocorr_upto.setText(_fromUtf8(""))
        self.autocorr_upto.setObjectName(_fromUtf8("autocorr_upto"))
        self.autocorr = QtGui.QCheckBox(self.groupBox_8)
        self.autocorr.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.autocorr.setObjectName(_fromUtf8("autocorr"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 400, 651, 71))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_16 = QtGui.QLabel(self.groupBox_9)
        self.label_16.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.kld_l = QtGui.QLineEdit(self.groupBox_9)
        self.kld_l.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.kld_l.setText(_fromUtf8(""))
        self.kld_l.setObjectName(_fromUtf8("kld_l"))
        self.kld = QtGui.QCheckBox(self.groupBox_9)
        self.kld.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.kld.setObjectName(_fromUtf8("kld"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 480, 651, 71))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_17 = QtGui.QLabel(self.groupBox_10)
        self.label_17.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.l1m_upto = QtGui.QLineEdit(self.groupBox_10)
        self.l1m_upto.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.l1m_upto.setText(_fromUtf8(""))
        self.l1m_upto.setObjectName(_fromUtf8("l1m_upto"))
        self.l1m = QtGui.QCheckBox(self.groupBox_10)
        self.l1m.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.l1m.setObjectName(_fromUtf8("l1m"))
        self.analyze = QtGui.QPushButton(self.tab_4)
        self.analyze.setGeometry(QtCore.QRect(290, 570, 98, 27))
        self.analyze.setObjectName(_fromUtf8("analyze"))
        self.analyze_bar = QtGui.QProgressBar(self.tab_4)
        self.analyze_bar.setGeometry(QtCore.QRect(260, 610, 161, 23))
        self.analyze_bar.setProperty("value", 0)
        self.analyze_bar.setObjectName(_fromUtf8("analyze_bar"))
        self.an_seq_len = QtGui.QLineEdit(self.tab_4)
        self.an_seq_len.setGeometry(QtCore.QRect(210, 20, 121, 27))
        self.an_seq_len.setObjectName(_fromUtf8("an_seq_len"))
        self.label_40 = QtGui.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(50, 20, 131, 20))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.plot = QtGui.QPushButton(self.tab_5)
        self.plot.setGeometry(QtCore.QRect(290, 350, 98, 27))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 20, 651, 71))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.plot_entropy = QtGui.QCheckBox(self.groupBox_13)
        self.plot_entropy.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.plot_entropy.setObjectName(_fromUtf8("plot_entropy"))
        self.eval_l = QtGui.QLineEdit(self.groupBox_13)
        self.eval_l.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.eval_l.setText(_fromUtf8(""))
        self.eval_l.setObjectName(_fromUtf8("eval_l"))
        self.label_19 = QtGui.QLabel(self.groupBox_13)
        self.label_19.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 100, 651, 71))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_21 = QtGui.QLabel(self.groupBox_14)
        self.label_21.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.plot_upto = QtGui.QLineEdit(self.groupBox_14)
        self.plot_upto.setGeometry(QtCore.QRect(240, 30, 41, 30))
        self.plot_upto.setText(_fromUtf8(""))
        self.plot_upto.setObjectName(_fromUtf8("plot_upto"))
        self.plot_autocorr = QtGui.QCheckBox(self.groupBox_14)
        self.plot_autocorr.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.plot_autocorr.setObjectName(_fromUtf8("plot_autocorr"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 180, 651, 71))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.plot_kld = QtGui.QCheckBox(self.groupBox_15)
        self.plot_kld.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.plot_kld.setObjectName(_fromUtf8("plot_kld"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 260, 651, 71))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.plot_l1m = QtGui.QCheckBox(self.groupBox_16)
        self.plot_l1m.setGeometry(QtCore.QRect(40, 30, 97, 22))
        self.plot_l1m.setObjectName(_fromUtf8("plot_l1m"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        projectgui.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(projectgui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        projectgui.setStatusBar(self.statusbar)

        self.retranslateUi(projectgui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(projectgui)

    def retranslateUi(self, projectgui):
        projectgui.setWindowTitle(_translate("projectgui", "MainWindow", None))
        self.label.setText(_translate("projectgui", "Graph path:", None))
        self.groupBox.setTitle(_translate("projectgui", "Terminations", None))
        self.old_term.setText(_translate("projectgui", "Old", None))
        self.new_term.setText(_translate("projectgui", "New", None))
        self.omega_term.setText(_translate("projectgui", "Omega", None))
        self.omega_inverted_term.setText(_translate("projectgui", "Omega Inverse", None))
        self.dmark_term.setText(_translate("projectgui", "D-Markov", None))
        self.groupBox_2.setTitle(_translate("projectgui", "Algorithms", None))
        self.mk1.setText(_translate("projectgui", "Mk1", None))
        self.mk2.setText(_translate("projectgui", "Mk2", None))
        self.dmark.setText(_translate("projectgui", "D-Markov", None))
        self.mk2_moore.setText(_translate("projectgui", "Mk2 w/ Moore", None))
        self.mk3.setText(_translate("projectgui", "Mk3", None))
        self.crissis.setText(_translate("projectgui", "CRiSSiS", None))
        self.groupBox_3.setTitle(_translate("projectgui", "D-Markov Parameters", None))
        self.label_2.setText(_translate("projectgui", "D from:", None))
        self.label_3.setText(_translate("projectgui", "to:", None))
        self.groupBox_4.setTitle(_translate("projectgui", "Mk1 and Mk2 Parameters", None))
        self.label_4.setText(_translate("projectgui", "L from:", None))
        self.label_5.setText(_translate("projectgui", "to:", None))
        self.label_6.setText(_translate("projectgui", "to:", None))
        self.label_7.setText(_translate("projectgui", "alpha from:", None))
        self.label_8.setText(_translate("projectgui", "Tag:", None))
        self.saveconfig.setText(_translate("projectgui", "Save Config", None))
        self.loadconfig.setText(_translate("projectgui", "Load Config", None))
        self.label_18.setText(_translate("projectgui", "Max L:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("projectgui", "General Configurations", None))
        self.create_term.setText(_translate("projectgui", "Create Terminations", None))
        self.create_dmark.setText(_translate("projectgui", "Create D-Markovs", None))
        self.apply_algo.setText(_translate("projectgui", "Apply Algorithms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("projectgui", "Graph Generation", None))
        self.gen_seq.setText(_translate("projectgui", "Generate Sequence", None))
        self.label_9.setText(_translate("projectgui", "Sequence Length:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("projectgui", "Sequence Generation", None))
        self.groupBox_5.setTitle(_translate("projectgui", "Sub-sequence Probabilities", None))
        self.label_10.setText(_translate("projectgui", "Max lenght:", None))
        self.probs.setText(_translate("projectgui", "Enable", None))
        self.groupBox_6.setTitle(_translate("projectgui", "Sub-sequence Conditional Probabilities", None))
        self.label_11.setText(_translate("projectgui", "Max lenght:", None))
        self.cond_probs.setText(_translate("projectgui", "Enable", None))
        self.label_39.setText(_translate("projectgui", "Sequence Length:", None))
        self.groupBox_7.setTitle(_translate("projectgui", "Conditional Entropy", None))
        self.label_13.setText(_translate("projectgui", "Max lenght:", None))
        self.cond_entropy.setText(_translate("projectgui", "Enable", None))
        self.groupBox_8.setTitle(_translate("projectgui", "Autocorrelation", None))
        self.label_15.setText(_translate("projectgui", "Up to:", None))
        self.autocorr.setText(_translate("projectgui", "Enable", None))
        self.groupBox_9.setTitle(_translate("projectgui", "Kullback-Leibler Divergence", None))
        self.label_16.setText(_translate("projectgui", "Length:", None))
        self.kld.setText(_translate("projectgui", "Enable", None))
        self.groupBox_10.setTitle(_translate("projectgui", "L1-Metric", None))
        self.label_17.setText(_translate("projectgui", "Up to:", None))
        self.l1m.setText(_translate("projectgui", "Enable", None))
        self.analyze.setText(_translate("projectgui", "Analyze", None))
        self.label_40.setText(_translate("projectgui", "Sequence Length:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("projectgui", "Sequence Analysis", None))
        self.plot.setText(_translate("projectgui", "Plot", None))
        self.groupBox_13.setTitle(_translate("projectgui", "Conditional Entropy", None))
        self.plot_entropy.setText(_translate("projectgui", "Enable", None))
        self.label_19.setText(_translate("projectgui", "At:", None))
        self.groupBox_14.setTitle(_translate("projectgui", "Autocorrelation", None))
        self.label_21.setText(_translate("projectgui", "Up to:", None))
        self.plot_autocorr.setText(_translate("projectgui", "Enable", None))
        self.groupBox_15.setTitle(_translate("projectgui", "Kullback-Leibler Divergence", None))
        self.plot_kld.setText(_translate("projectgui", "Enable", None))
        self.groupBox_16.setTitle(_translate("projectgui", "L1-Metric", None))
        self.plot_l1m.setText(_translate("projectgui", "Enable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("projectgui", "Plot Results", None))

