algorithms: [mk2_moore, dmark, mk1, crissis]
alpharange: []
drange: [2, 3, 4, 5, 6, 7, 8]
graph_path: logisticmap
l2range: [1]
lmax: 10
lrange: [2, 4, 6, 8]
synch_words: ['2', '11', '00']
terminations: [dmark, omega_inverted]
test: chi-squared
