algorithms: [dmark, crissis]
alpharange: [0.95]
drange: [4, 5, 6, 7, 8, 9]
graph_path: logisticmap
l2range: [1, 2]
lmax: 10
lrange: [1]
synch_words: ['2', '11', '00', '01', '10']
terminations: []
test: chi-squared
