algorithms: [mk2_moore, dmark, crissis]
alpharange: [0.95]
drange: [4, 5, 6, 7, 8, 9, 10]
graph_path: logisticmap
l2range: [1, 2, 3, 4]
lmax: 10
lrange: [4, 6, 8, 10]
synch_words: ['2', '11', '00', '01', '10']
terminations: [dmark, omega_inverted]
test: chi-squared
