algorithms: [crissis]
alpharange: [0.95]
drange: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
graph_path: tsw
l2range: [1, 2, 3, 4]
lmax: 12
lrange: [1]
synch_words: ['01', '00', '10', '1111']
terminations: []
test: chi-squared
