algorithms: [mk2_moore, dmark, mk1, crissis]
alpharange: [0.95]
drange: [2, 3, 4, 5, 6, 7, 8, 9, 10]
graph_path: tsw
l2range: [1, 2]
lmax: 18
lrange: [2, 4, 6, 8, 10]
synch_words: ['00', '01', '10', '1111']
terminations: [dmark, omega_inverted]
test: chi-squared
