algorithms: [mk2_moore, dmark, mk1, crissis]
alpharange: [0.95]
drange: [2, 3, 4, 5, 6, 7, 8]
graph_path: ternary10db
l2range: [1, 2, 3, 4]
lmax: 10
lrange: [2, 4, 6, 8]
synch_words: ['2', '11', '00']
terminations: [dmark, omega_inverted]
test: chi-squared
