algorithms: [mk2_moore, dmark, mk1, crissis]
alpharange: [0.95]
drange: [4, 5, 6, 7, 8]
graph_path: vanderpol
l2range: [1]
lmax: 10
lrange: [4, 6, 8, 10]
synch_words: ['12', '111', '01', '10', '21']
terminations: [dmark, omega_inverted]
test: chi-squared
