algorithms: [mk2_moore, dmark, crissis]
alpharange: [0.95]
drange: [2, 3, 4, 5, 6, 7, 8, 9, 10]
graph_path: dk_35
l2range: [1, 2, 3, 4]
lmax: 12
lrange: [2, 4, 6, 8, 10]
synch_words: ['0', '11111']
terminations: [dmark, omega_inverted]
test: chi-squared
